### ISSUE TITLE
3dstreet asset loader to support a-frame latest

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#240]
Tried this once and only saw blue loading screen and got this console error:
> Uncaught TypeError: window.AFRAME.registerElement is not a function

We use registerElement for assets.js here:
https://github.com/3DStreet/3dstreet/blob/main/src/assets.js#L248

May be related to:
https://github.com/aframevr/aframe/pull/5136

**Comment by kfarr** [comment]
Some next steps from Vincent:
* Create an issue on A-Frame repo. At least reintroduce the api as an alias or remove it from documentation, there is still a reference to it in docs/core/globals.md.
* Here your code use createdCallback attachedCallback so it's definitely a custom element, it seems inspired from a-assets. attachedCallback is now called connectedCallback. To create a custom element, you now create a class inheriting from ANode. Really look at src/core/a-assets.js how it is now and recreate your custom street-assets from it with your changes
* https://github.com/aframevr/aframe/pull/5226

From Will:
* it looks like you're defining custom elements.
* In 1.4 A-Frame switch to the native custom elements implementation in browsers, so you can get the same effect with
class StreetAssets extends window.AFRAME.AEntity {} and window.customElements.define('street-assets', StreetAssets)
Example here: https://glitch.com/edit/#!/glimmer-phantom-lyre?path=comp.js%3A3%3A11 (edited)

**Comment by kfarr** [comment]
cc @zach-capalbo as this might also affect vartiste working with aframe 1.4

**Comment by kfarr** [comment]
https://github.com/c-frame/aframe-cursor-teleport/issues/29

**Comment by kfarr** [comment]
Reminder of the goals of 3dstreet asset loader (why go through this pain?)
* be able to separate asset and mixin definition into separate file for maintainability (>200 assets)
* be able to dynamically set asset domain to match dev vs. production environments (between CDN, local or other)
* based on @zach-capalbo's https://gitlab.com/zach-geek/vartiste/-/blob/release/src/assets.js

Here is the current state of asset loader v2 to support a-frame latest:
* glitch test project: https://glitch.com/edit/#!/3dstreet-asset-loader-v2?path=index.html%3A20%3A7
* it "works" in that it injects the desired assets
* however it does not "block" loading of those assets until they are complete -- I am concerned this will result in errors in the future

I have attempted to make a "blocking" version which you can access this way:
* [line 37](https://glitch.com/edit/#!/3dstreet-asset-loader-v2?path=assetsv2.js%3A37%3A4) and [line 78](https://glitch.com/edit/#!/3dstreet-asset-loader-v2?path=assetsv2.js%3A78%3A4) of assetsv2.js in the glitch project are commented out. Uncomment them to see my attempt at "blocking" the scene from loading until the assets are complete. However instead of blocking, the newly injected assets do not load at all.

Question:
* Is there another way to trigger the asset loader to load and wait for completion of the newly inserted inlinehtml assets?
* Is there a danger in not having the loader block -- or is ok to accept that this new loader will insert the 3dstreet assets but not block loading?

**Comment by vincentfretin** [comment]
Your StreetAssets node mixing both a-assets and a-asset-item implementation make it hard to understand what's going on. Now that I understand what your node is doing, actually just inserting some html to add additional assets, I rewrote a simpler version of it, just adding the additional assets under a-assets so that it is processed with the original implementation. This seems to be blocking alright, the loading screen disappears only once the glb is downloaded.

```js
/* global THREE, AFRAME, customElements */

const ANode = AFRAME.ANode;

class StreetAssets extends ANode {
  constructor () {
    super();
    this.isAssetItem = true;
  }

  connectedCallback () {
    // var categories = this.getAttribute('categories');
    this.insertAdjacentHTML('afterend', `
    <a-asset-item id="box-truck-rigged" src="https://assets.3dstreet.app/sets/vehicles-rig/gltf-exports/draco/isuzu-truck-rig.glb"></a-asset-item>
    <a-mixin id="box-truck-rig" gltf-model="#box-truck-rigged" ></a-mixin>`)
    ANode.prototype.load.call(self);
  }
}

customElements.define('street-assets', StreetAssets);
```

https://glitch.com/edit/#!/awesome-global-pedestrian?path=assetsv2.js

**Comment by kfarr** [comment]
Hi @vincentfretin you're right it was a bit over complicated, sorry about that. Your solution looks great. I did one minor edit to get rid of an error* but it appears to satisfy all the goals we set out for the custom loader.

* Just add `const self = this;` in connectedCallback so the load function has a valid object.

**Comment by vincentfretin** [comment]
Oh my bad, I removed the `const self = this;` at the last minute without testing. :)

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet/pull/266
